### ISSUE TITLE
不能通过$scope.showGoto设置显示与否？

### ISSUE THREAD

**Issue by lunix01** [leonwgc/angularjs-pagination#2]
如题

**Comment by leonwgc** [comment]
**方法 1 ：** 
修改源码配置isolate scope 增加showGoto如下：
 scope: {
          pageCount: '=',
          currentPage: '=',
          showGoto:'=',
          onPageChange: '&'
        }

pager page-count="pageCount" current-page="currentPage" on-page-change="onPageChange()" show-goto='showGoto'


**方法2**
用angular的{{}} 去动态解析
pager page-count="pageCount" current-page="currentPage" on-page-change="onPageChange()" show-goto='{{showGoto}}'
