### ISSUE TITLE
visiblePageCount 参数错误

### ISSUE THREAD

**Issue by nanomt88** [leonwgc/angularjs-pagination#3]
页面设置了 visiblePageCount 参数，但是显示是错的！！！ 原因 是： 代码中  attrs.visiblePageCount 获取到 页面的配置是 字符串， 不是 integer ，计算显示的分页的时候  就算错了。 
（大哥，写完了你有测一下吗......）

**Comment by leonwgc** [comment]
抱歉，fix掉了，
var visiblePageCount = angular.isDefined(attrs.visiblePageCount) ? ~~attrs.visiblePageCount || ngPaginationConfig.visiblePageCount : ngPaginationConfig.visiblePageCount;
